spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/qsdy/config-repo-demo/
          username: 874289852@qq.com
          password: a5481087
server:
  port: 8003